[package]
name = "contacts"
version = "0.1.0"
edition = "2024"

[dependencies]
proj-server = { version = "0.1.0", path = "../../crates/proj-server" }
ron = "0.12.2"
same-file = "1.0.6"
serde = "1.0.229"
smol = "2.0.2"
toml = "1.1.6"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
